"""empty message

Revision ID: 275e4f25fc03
Revises: e99e185464f8
Create Date: 2019-11-18 14:08:11.191653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275e4f25fc03'
down_revision = 'e99e185464f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
