"""empty message

Revision ID: 429be4efcab8
Revises: 275e4f25fc03
Create Date: 2019-11-21 08:53:34.978979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429be4efcab8'
down_revision = '275e4f25fc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET admin=False")
    op.execute("UPDATE users SET admin=True WHERE username='patrick-admin'")
    op.alter_column("users", "admin", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
